# This is a basic workflow to help you get started with Actions

name: cli-sp-login

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Get these creds by running the following command:
      #  az ad sp create-for-rbac --name "myApp" --role contributor \
      #                      --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group} \
      #                      --sdk-auth
      # Add the response to the AZURE_CREDENTIALS
      # https://github.com/Azure/login#configure-a-service-principal-with-a-secret
        
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account show
            az storage -h
